#! /bin/sh

# Start user services and key listener
systemctl --user start user-graphical.target
sxhkd &

# Restore wallpaper
wal -R &

# Fix mouse cursor
xsetroot -cursor_name left_ptr

# Desktops
bspc monitor -d        
bspc config border_width	0
bspc config window_gap		0

# Monocles
bspc config gapless_monocle	true
bspc config borderless_monocle	true
bspc config single_monocle	 true

# Settings
bspc config focus_follows_pointer  true
bspc config split_ratio          0.5
bspc config focus_by_distance    true
bspc config history_aware_focus  true

# Rules
bspc rule -a Nightly desktop=^1 state=tiled
bspc rule -a Nightly:Browser state=floating
bspc rule -a Nightly:Dialog state=floating
bspc rule -a Nightly:firefox state=floating
bspc rule -a Nightly:Prompt state=floating
bspc rule -a "TelegramDesktop"
bspc rule -a "spotify" desktop=^5
bspc rule -a Android_Studio state=tiled

# Scripts
bspc subscribe desktop_focus | while read line; do bspc node -f pointed; done & disown

# Color scheme
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color15"

